In [1]:
import re
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv("wikipedia_train.csv", sep=',').fillna(0)
test = pd.read_csv("wikipedia_test.csv", sep=',').fillna(0)

In [3]:
train.head()

,Page,2015-07-01,2015-07-02,2015-07-03,2015-07-04,2015-07-05,2015-07-06,2015-07-07,2015-07-08,2015-07-09,...,2016-08-22,2016-08-23,2016-08-24,2016-08-25,2016-08-26,2016-08-27,2016-08-28,2016-08-29,2016-08-30,2016-08-31
0,15._November_de.wikipedia.org_desktop_all-agents,32.0,26.0,22.0,22.0,29.0,49.0,20.0,27.0,19.0,...,29.0,23.0,31.0,25.0,27.0,23.0,17.0,26.0,23.0,37.0
1,2012_(film)_fr.wikipedia.org_all-access_spider,2.0,3.0,5.0,3.0,5.0,3.0,7.0,8.0,7.0,...,5.0,5.0,6.0,5.0,4.0,11.0,2.0,0.0,7.0,5.0
2,2016_FIFA_U-20女子ワールドカップ_ja.wikipedia.org_all-a...,1.0,3.0,2.0,2.0,1.0,10.0,2.0,1.0,4.0,...,4.0,3.0,2.0,3.0,2.0,4.0,2.0,0.0,5.0,4.0
3,2016_UEFA_Europa_League_Final_en.wikipedia.org...,3.0,3.0,3.0,8.0,12.0,12.0,8.0,12.0,23.0,...,10.0,14.0,26.0,5.0,29.0,23.0,17.0,16.0,12.0,14.0
4,2016_in_video_gaming_en.wikipedia.org_all-acce...,24.0,40.0,23.0,49.0,88.0,25.0,31.0,76.0,51.0,...,134.0,162.0,208.0,179.0,108.0,99.0,49.0,80.0,113.0,173.0

In [4]:
test.head()

,Page,2016-09-10,2016-09-11,2016-09-12,2016-09-13,2016-09-14,2016-09-15,2016-09-16,2016-09-17,2016-09-18,...,2016-11-01,2016-11-02,2016-11-03,2016-11-04,2016-11-05,2016-11-06,2016-11-07,2016-11-08,2016-11-09,2016-11-10
0,15._November_de.wikipedia.org_desktop_all-agents,43.0,29.0,19.0,33.0,30.0,28.0,27.0,15.0,22.0,...,66.0,78.0,119.0,78.0,63.0,89.0,141.0,146.0,120.0,147.0
1,2012_(film)_fr.wikipedia.org_all-access_spider,6.0,31.0,23.0,12.0,1.0,24.0,9.0,30.0,4.0,...,2.0,0.0,3.0,2.0,6.0,1.0,2.0,1.0,3.0,2.0
2,2016_FIFA_U-20女子ワールドカップ_ja.wikipedia.org_all-a...,4.0,2.0,0.0,5.0,3.0,2.0,4.0,3.0,0.0,...,16.0,17.0,11.0,18.0,20.0,25.0,13.0,19.0,22.0,33.0
3,2016_UEFA_Europa_League_Final_en.wikipedia.org...,15.0,15.0,8.0,11.0,15.0,14.0,13.0,18.0,18.0,...,14.0,13.0,14.0,20.0,16.0,11.0,26.0,16.0,11.0,13.0
4,2016_in_video_gaming_en.wikipedia.org_all-acce...,101.0,35.0,80.0,191.0,199.0,301.0,174.0,155.0,136.0,...,94.0,104.0,85.0,108.0,110.0,109.0,221.0,75.0,63.0,101.0

In [5]:
train.shape, test.shape

((939, 429), (939, 63))

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 939 entries, 0 to 938
Columns: 429 entries, Page to 2016-08-31
dtypes: float64(428), object(1)
memory usage: 3.1+ MB

In [7]:
for col in train.columns[1:]:
    train[col] = pd.to_numeric(train[col], downcast='integer')
train.head()

,Page,2015-07-01,2015-07-02,2015-07-03,2015-07-04,2015-07-05,2015-07-06,2015-07-07,2015-07-08,2015-07-09,...,2016-08-22,2016-08-23,2016-08-24,2016-08-25,2016-08-26,2016-08-27,2016-08-28,2016-08-29,2016-08-30,2016-08-31
0,15._November_de.wikipedia.org_desktop_all-agents,32,26,22,22,29,49,20,27,19,...,29,23,31,25,27,23,17,26,23,37
1,2012_(film)_fr.wikipedia.org_all-access_spider,2,3,5,3,5,3,7,8,7,...,5,5,6,5,4,11,2,0,7,5
2,2016_FIFA_U-20女子ワールドカップ_ja.wikipedia.org_all-a...,1,3,2,2,1,10,2,1,4,...,4,3,2,3,2,4,2,0,5,4
3,2016_UEFA_Europa_League_Final_en.wikipedia.org...,3,3,3,8,12,12,8,12,23,...,10,14,26,5,29,23,17,16,12,14
4,2016_in_video_gaming_en.wikipedia.org_all-acce...,24,40,23,49,88,25,31,76,51,...,134,162,208,179,108,99,49,80,113,173

In [8]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 939 entries, 0 to 938
Columns: 429 entries, Page to 2016-08-31
dtypes: int16(145), int32(283), object(1)
memory usage: 1.3+ MB

In [9]:
for coll in test.columns[1:]:
    test[coll] = pd.to_numeric(test[coll], downcast='integer')
test.head()

,Page,2016-09-10,2016-09-11,2016-09-12,2016-09-13,2016-09-14,2016-09-15,2016-09-16,2016-09-17,2016-09-18,...,2016-11-01,2016-11-02,2016-11-03,2016-11-04,2016-11-05,2016-11-06,2016-11-07,2016-11-08,2016-11-09,2016-11-10
0,15._November_de.wikipedia.org_desktop_all-agents,43,29,19,33,30,28,27,15,22,...,66,78,119,78,63,89,141,146,120,147
1,2012_(film)_fr.wikipedia.org_all-access_spider,6,31,23,12,1,24,9,30,4,...,2,0,3,2,6,1,2,1,3,2
2,2016_FIFA_U-20女子ワールドカップ_ja.wikipedia.org_all-a...,4,2,0,5,3,2,4,3,0,...,16,17,11,18,20,25,13,19,22,33
3,2016_UEFA_Europa_League_Final_en.wikipedia.org...,15,15,8,11,15,14,13,18,18,...,14,13,14,20,16,11,26,16,11,13
4,2016_in_video_gaming_en.wikipedia.org_all-acce...,101,35,80,191,199,301,174,155,136,...,94,104,85,108,110,109,221,75,63,101

In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 939 entries, 0 to 938
Columns: 429 entries, Page to 2016-08-31
dtypes: int16(145), int32(283), object(1)
memory usage: 1.3+ MB

In [11]:
def get_language(page):
    res = re.search('[a-z][a-z].wikipedia.org', page)
    if res:
        return res[0][0:2]
    return 'na'

In [12]:
train.Page.map(get_language).value_counts()

en    140
fr    128
na    124
ja    124
de    122
ru    102
es    101
zh     98
Name: Page, dtype: int64

## Сколько страниц из русской Википедии в датасете?

Відповідь: 102

In [13]:
train[train.Page.map(get_language) == 'ru'].\
    mean(axis=1).sort_values(ascending=False).head()

180    2171.240654
725    1873.478972
666    1856.995327
685    1787.502336
689    1708.794393
dtype: float64

In [14]:
train.loc[180]['Page']

'Facebook_ru.wikipedia.org_desktop_all-agents'

## Какая самая популярная страница русской Википедии (в среднем) на train?

**Facebook_ru.wikipedia.org_desktop_all-agents**

In [15]:
train = pd.melt(train, id_vars='Page', var_name='date', value_name='Visits')

In [16]:
train.tail()

                                              Page        date  Visits
401887  黃義雄_zh.wikipedia.org_all-access_all-agents  2016-08-31      20
401888   黄渤_zh.wikipedia.org_all-access_all-agents  2016-08-31     414
401889  黑嘉嘉_zh.wikipedia.org_all-access_all-agents  2016-08-31     360
401890      黒木瞳_ja.wikipedia.org_all-access_spider  2016-08-31     304
401891   齊秦_zh.wikipedia.org_mobile-web_all-agents  2016-08-31     121

In [19]:
df_train = train[train['date'] == '2016-08-31']

In [20]:
df_train = df_train.reset_index(drop=True)

In [21]:
df_train.head()

                                                Page        date  Visits
0   15._November_de.wikipedia.org_desktop_all-agents  2016-08-31      37
1     2012_(film)_fr.wikipedia.org_all-access_spider  2016-08-31       5
2  2016_FIFA_U-20女子ワールドカップ_ja.wikipedia.org_all-a...  2016-08-31       4
3  2016_UEFA_Europa_League_Final_en.wikipedia.org...  2016-08-31      14
4  2016_in_video_gaming_en.wikipedia.org_all-acce...  2016-08-31     173

In [22]:
df_train.tail()

                                           Page        date  Visits
934  黃義雄_zh.wikipedia.org_all-access_all-agents  2016-08-31      20
935   黄渤_zh.wikipedia.org_all-access_all-agents  2016-08-31     414
936  黑嘉嘉_zh.wikipedia.org_all-access_all-agents  2016-08-31     360
937      黒木瞳_ja.wikipedia.org_all-access_spider  2016-08-31     304
938   齊秦_zh.wikipedia.org_mobile-web_all-agents  2016-08-31     121

In [29]:
test = pd.melt(test, id_vars='Page', var_name='date', value_name='Visits')

In [30]:
test.head()

                                                Page        date  Visits
0   15._November_de.wikipedia.org_desktop_all-agents  2016-09-10      43
1     2012_(film)_fr.wikipedia.org_all-access_spider  2016-09-10       6
2  2016_FIFA_U-20女子ワールドカップ_ja.wikipedia.org_all-a...  2016-09-10       4
3  2016_UEFA_Europa_League_Final_en.wikipedia.org...  2016-09-10      15
4  2016_in_video_gaming_en.wikipedia.org_all-acce...  2016-09-10     101

In [31]:
df_test = test[test['date'] == '2016-09-10']

In [32]:
df_test.reset_index(drop=True).head()

                                                Page        date  Visits
0   15._November_de.wikipedia.org_desktop_all-agents  2016-09-10      43
1     2012_(film)_fr.wikipedia.org_all-access_spider  2016-09-10       6
2  2016_FIFA_U-20女子ワールドカップ_ja.wikipedia.org_all-a...  2016-09-10       4
3  2016_UEFA_Europa_League_Final_en.wikipedia.org...  2016-09-10      15
4  2016_in_video_gaming_en.wikipedia.org_all-acce...  2016-09-10     101

In [33]:
df_test.tail()

                                           Page        date  Visits
934  黃義雄_zh.wikipedia.org_all-access_all-agents  2016-09-10    2406
935   黄渤_zh.wikipedia.org_all-access_all-agents  2016-09-10     446
936  黑嘉嘉_zh.wikipedia.org_all-access_all-agents  2016-09-10      92
937      黒木瞳_ja.wikipedia.org_all-access_spider  2016-09-10      59
938   齊秦_zh.wikipedia.org_mobile-web_all-agents  2016-09-10     645

In [34]:
df_train.rename(columns={"Visits": "pred_Visits"}, inplace=True)

In [ ]:
df_test = pd.concat([df_test, df_train["pred_Visits"]], axis=1)

In [ ]:
df_test.head()

In [ ]:
def pandas_smape(df):
    df.fillna(0, inplace=True)
    df["SMAPE"] = 200 * np.abs(df["Visits"] - df["pred_Visits"]) / (df["Visits"] + df["pred_Visits"])
    df["SMAPE"].fillna(0, inplace=True)
    return np.mean(df["SMAPE"])

In [ ]:
round(pandas_smape(df_test), 2)

In [ ]:
train

In [ ]:
median_baseline = new_train.loc[new_train["date"] > '2016-08-01'].groupby(['Page']).median().reset_index()

In [ ]:
median_baseline.rename(columns={"Visits": "pred_Visits"}, inplace=True)

In [ ]:
pandas_smape(new_test.merge(median_baseline, on="Page", how='left'))

In [ ]:
new_train['date'] = pd.to_datetime(new_train['date'])
new_test['date'] = pd.to_datetime(new_test['date'])

In [ ]:
new_train['Month']     = new_train["date"].dt.month
new_train['Day']       = new_train["date"].dt.day
new_train['DayOfWeek'] = new_train["date"].dt.dayofweek

new_test['Month']     = new_test["date"].dt.month
new_test['Day']       = new_test["date"].dt.day
new_test['DayOfWeek'] = new_test["date"].dt.dayofweek

In [ ]:
new_train["weekend"] = ((new_train["date"].dt.dayofweek) // 5 == 1).astype(int)
new_test["weekend"] = ((new_test["date"].dt.dayofweek) // 5 == 1).astype(int)

In [ ]:
median_weekend_baseline = new_train.loc[new_train["date"] > '2016-08-01'].groupby(['Page', 'weekend']).median().reset_index()
median_weekend_baseline.rename(columns={"Visits": "pred_Visits"}, inplace=True)

In [ ]:
pandas_smape(new_test.merge(median_weekend_baseline, on=["Page", "weekend"], how='left'))

In [ ]:
from dateutil.relativedelta import relativedelta

In [ ]:
windows = [7, 10, 12, 14, 25, 30, 60, 120, 240, 360, 365]

In [ ]:
for w in windows:
    start_day = new_train['date'].max() - relativedelta(days=w)
    median_weekend_baseline = new_train.loc[new_train["date"] > start_day].groupby(['Page', 'weekend']).median().reset_index()
    median_weekend_baseline.rename(columns={"Visits": "pred_Visits"}, inplace=True)
    print(w, pandas_smape(new_test.merge(median_weekend_baseline, on=["Page", "weekend"], how='left')))